# Required environment variables:
#
#  * ORG_GRADLE_PROJECT_systemProp.sonar.login=
#  * ORG_GRADLE_PROJECT_systemProp.sonar.password=
#
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
env:
  global:
    - GRADLE_OPTS=-XX:MaxPermSize=256m
    - "ORG_GRADLE_PROJECT_systemProp.sonar.host.url"=https://sonar.mnode.org
before_script:
  - sudo keytool -import -alias sonar -keystore $JAVA_HOME/jre/lib/security/cacerts -file sonar_cert.pem -storepass changeit -noprompt
script:
  - ./gradlew check sonarqube
before_deploy: "./gradlew assembleDist"
sudo: true
deploy:
  provider: releases
  api_key:
    secure: DzdK3o3QFvQtKGtHl74j9geBg5uaFnasQXrNWWb5SRBfjDAhjQd49Ju5Pu8n5+W2SMUvB5w4KXepmHgu4R8Q9jo9tI/oTN6XB+0RJE+09rNQfeUEcYM6PLrBt0AZLfcQqkWxNkW+KvwhGb080loPKoTLI6VtLenkG19T4/z/qxo=
  file:
    - build/distributions/ical4j-extensions-$RELEASE_VERSION.zip
    - build/distributions/ical4j-extensions-$RELEASE_VERSION.tgz
  skip_cleanup: true
  on:
    tags: true
addons:
  hostname: travis-ci
